Avoiding loops with numpy
==============

Instead of using `for` loops to perform basic matrix or vector computations on different inputs, it is often possible to calculate all results with a single call to a numpy function, which should be much faster than using a `for` loop. For instance, you can replace multiple matrix-vector multiplications by a single matrix-matrix multiplication.

In order to get the desired result it might be necessary to transpose the input or output matrixes. This can get a little confusing, especially if you are used to column vectors but want to use row vectors in python instead. This documents provides some information and examples on how to perform multiple matrix and vector computations at once using numpy function.

Nomenclature
--------------

This section describes some basic notation. Matrixes are represented by capital letters (A, B), vectors by lower-case letters a, b. Whenever an index appears twice in a product, this referes to the sum of the product over all instances of the index. $A_{ik} B_{kj} = \sum_k A_{ik} B_{kj}$.

Further:
- $ab$: Scalar product of a and b with $ab=a_k b_k$
- $AB$: Matrix product of A and B with $(AB)_{ij} = A_{ik}B_{kj}$
- $A_{i:}=A[i,:]$: The i-th row vector of the matrix A
- $A_{:j}=A[:,j]$: The j-th column vector of the matrix A

The dot function
-------------------

For 1d arrays, the dot function returns the scalar product: ${\rm dot}(a,b) = a_k b_k$

In [2]:
from numpy import array, dot
x=array([1,2])
y=array([2,3])
dot(x,y)

8

For 2d arrays, the dot function returns the matrix product: ${\rm dot}(A, B)_{ij} = A_{ik}B_{kj}$. Note that the number of columns of $A$ need to be idendical to the number of rows in $B$ and that ${\rm dot}(A, B)$ has the same number as rows as $A$ and the same number of columns as $B$.

In [3]:
A=array([[1,2],
         [3,4]])
B=array([[2,3],
         [4,5]])
dot(A,B)

array([[10, 13],
       [22, 29]])

Note that the element $(AB)_{ij}$ is the scalar product of the i-th row vector of $A$ with the j-th column vector of $B$ and that $(AB)[:,j]$ is the result of the matrix vector multiplication of the matrix $A$ and the j-th column vector of B. 

Row vectors
-------------

While in mathematics it is common to work with column vectos, in python you usually want to work with row vectors.

In [4]:
A=array([[1,2],
         [3,4]])
A[0] #Return first row vector

array([1, 2])

In [5]:
A[:,0] #Return first column vector

array([1, 3])

Scalar product
----------------

The array $M$ with matrix element $M_{ij} = a_i b_j$ can be computed from the arrays A and B composed of the row vectors $a_i$ and $b_i$, respectively, with: $M={\rm dot}(A,B.T)$.

In [6]:
A=array([[1,2],
         [3,4]])
B=array([[2,3],
         [4,5]])
dot(A, B.T)

array([[ 8, 14],
       [18, 32]])

In order to compute the scalar products of a single vector v and multiple vectors $b_i$ simply use: $M={\rm dot}(v, B.T)$

In [7]:
v=array([1,2])
B=array([[2,3],
         [4,5]])
dot(v, B.T)

array([ 8, 14])

Matrix-vector multiplication
--------------------------------

The array $M$ with row vectors $M[i,:]=A b_i$ can be computed from the array B with row vectors $b_i$ with $M = {\rm dot}(B, A.T)$

In [8]:
A = array([[1, 2],
           [3, 4]])
B = array([[2, 3],
           [4, 5]])
dot(B, A.T)

array([[ 8, 18],
       [14, 32]])

Scalar-vector multiplication (n to 1)
-------------------------------------------

The array $M$ with row vectors $M[i,:] = \alpha_i v$ can be calculated from the vector $a$ with $a_i = \alpha_i$ with $M = {\rm dot}({\rm vstack}(a), {\rm vstack}(v).T)$. Alternatively, you may also compute $M = {\rm dot}({\rm vstack}(a), {\rm matrix}(v).T)$. However, this will return a matrix instead of an array object.

In [9]:
from numpy import vstack, newaxis
a = array([2, 3])
v = array([1, 2])
dot(vstack(a), v[newaxis])

array([[2, 4],
       [3, 6]])

Note that simple writing $a.T$ won't have an effect for a one dimensional array. Instead you may use $a[newaxis].T$ or ${\rm vstack}(a)$ as in the example above.

Scalar-vector multiplication (1 to 1)
--------------------------------------------

The array M with row vectors $M[i,:]=\alpha_i b_i$ can be caluclated from the vector $a$ with $a_i=\alpha_i$ and the array $B$ with row vector $b_i$ with $M={\rm vstack}(a)*B$.

In [10]:
from numpy import array, vstack
a=array([1,2])
B=array([[1,2],[2,3]])
vstack(a) * B

array([[1, 2],
       [4, 6]])